services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=josh@joshuawoodward.dev"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: ghcr.io/jmorton95/klavlor:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.web.rule=Host(`chart.joshuawoodward.dev`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.middlewares=global-rate-limit"
      - "traefik.http.middlewares.global-rate-limit.rateLimit.average=100"
      - "traefik.http.middlewares.global-rate-limit.rateLimit.burst=150"
    environment:
      - DatabaseSettings__Host=db
      - DatabaseSettings__Port=5432
      - DatabaseSettings__Database=klavlor
      - DatabaseSettings__Username=postgres
      - DatabaseSettings__Password=${DB_PASSWORD}
      - SystemConfiguration__SystemUsername=${SYSTEM_USERNAME}
      - SystemConfiguration__SystemPassword=${SYSTEM_PASSWORD}
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - db
        
  db:
    image: postgres:18.1
    user: postgres
    volumes:
      - database-data:/var/lib/postgresql
    secrets:
      - db-password
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-data:
  letsencrypt:

secrets:
  db-password:
    external: true
