<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>KlavLor.Infrastructure</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\KlavLor.Domain\KlavLor.Domain.csproj" />
        <ProjectReference Include="..\KlavLor.Application\KlavLor.Application.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="2.3.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
